### ISSUE TITLE
As Nattie, I want to receive system notifications so that I know what happens in the ecosystem.

### ISSUE THREAD

**Issue by molnarzs** [garlictech/yaha#25]
These are for the generic notifications for both guest and registered users.

### Resources

* Link to screen design: 
* Screen number in design: #3
* Link to flow design:
* Link to feature file

### Tasks

- [ ] create a "bell" icon with unread message number badge
- [ ] create a section displaying system notifications 
- [ ] the notification can be closed with X, then the next notification appears
- [ ] the notifications have an expiration time (ex. system is down - if the user does not open the notification before the system is up again, then don't display the notification)
- [ ] In case of notifications, send push notification.

### Acceptance Criteria

Linked e2e test must pass OR...

### Notes

N/A

Please also note:

1. If a conversation about the issue I’m working on is happening, the outcomes should be documented within that issue (not in the comments).

###  General resources:

* [Style-guides and template for a user story](agile-user-story.md)
* [“Advantages of the “As a user, I want” user story template.”](http://www.mountaingoatsoftware.com/blog/advantages-of-the-as-a-user-i-want-user-story-template)
* [Scrum guide](http://scrumguides.org/scrum-guide.html)
